In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7], 
                    "b": [2, 3, 4, 2, 3, 4, 5], 
                    "c": [3, 4, 5, 2, 3, 4, 5], 
                    "d": [4, 5, 6, 2, 3, 4, 5], 
                    "e": [5, 6, 7, 2, 3, 4, 5]})

In [3]:
df1

   a  b  c  d  e
0  1  2  3  4  5
1  2  3  4  5  6
2  3  4  5  6  7
3  4  2  2  2  2
4  5  3  3  3  3
5  6  4  4  4  4
6  7  5  5  5  5

## Method 1: Slice Columns in pandas using reindex

In [8]:
df2 = df1.reindex(columns=['c','e'])
print(df2)

   c  e
0  3  5
1  4  6
2  5  7
3  2  2
4  3  3
5  4  4
6  5  5

## Method 2: Slice Columns in pandas using loc[]
Syntax: [ : , first : last : step]

In [11]:
df3 = df1.loc[:,'b':'e' : 2]
df3

   b  d
0  2  4
1  3  5
2  4  6
3  2  2
4  3  3
5  4  4
6  5  5

In [12]:
df3 = df1.loc[:,'b':'e' : 1]
df3

   b  c  d  e
0  2  3  4  5
1  3  4  5  6
2  4  5  6  7
3  2  2  2  2
4  3  3  3  3
5  4  4  4  4
6  5  5  5  5

## Method 3: Slice Columns in pandas using iloc[]
Syntax: [ : ,start : stop : step]

In [13]:
df2 = df1.iloc[:, 1:3:1]
print(df2)

   b  c
0  2  3
1  3  4
2  4  5
3  2  2
4  3  3
5  4  4
6  5  5