In [1]:
import pandas as pd
import numpy as np

# Applying Lambda functions to Pandas Dataframe
Syntax: lambda arguments: expression

An anonymous function which we can pass in instantly without defining a name or any thing like a full traditional function.

### Dataframe.assign() on a Single Column

In [5]:
values= [['Rohan',455],['Elvish',250],['Deepak',495],
         ['Soni',400],['Radhika',350],['Vansh',450]] 

df = pd.DataFrame(values,columns=['Name','Total_Marks'])
df = df.assign(Percentage = lambda x : (x['Total_Marks']/500)*100)
df

      Name  Total_Marks  Percentage
0    Rohan          455        91.0
1   Elvish          250        50.0
2   Deepak          495        99.0
3     Soni          400        80.0
4  Radhika          350        70.0
5    Vansh          450        90.0

### Dataframe.assign() on Multiple Columns

In [8]:
values_list = [[15, 2.5, 100], [20, 4.5, 50], [25, 5.2, 80],
               [45, 5.8, 48], [40, 6.3, 70], [41, 6.4, 90],
               [51, 2.3, 111]]

df = pd.DataFrame(values_list , columns=['List1','List2','List3'])
df = df.assign(Product = lambda x : x['List1'] * x['List2'] * x['List3'])
df

   List1  List2  List3  Product
0     15    2.5    100   3750.0
1     20    4.5     50   4500.0
2     25    5.2     80  10400.0
3     45    5.8     48  12528.0
4     40    6.3     70  17640.0
5     41    6.4     90  23616.0
6     51    2.3    111  13020.3

### Dataframe.apply() on a Single Row

In [13]:
values_list = [[15, 2.5, 100], [20, 4.5, 50], [25, 5.2, 80],
               [45, 5.8, 48], [40, 6.3, 70], [41, 6.4, 90], 
               [51, 2.3, 111]]

df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'],
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])

df = df.apply(lambda x: np.square(x) if x.name == 'd' else x,axis=1)

df

   Field_1  Field_2  Field_3
a     15.0     2.50    100.0
b     20.0     4.50     50.0
c     25.0     5.20     80.0
d   2025.0    33.64   2304.0
e     40.0     6.30     70.0
f     41.0     6.40     90.0
g     51.0     2.30    111.0

### Dataframe.apply() on Multiple Rows

In [14]:
values_list = [[15, 2.5, 100], [20, 4.5, 50], [25, 5.2, 80],
               [45, 5.8, 48], [40, 6.3, 70], [41, 6.4, 90], 
               [51, 2.3, 111]]

df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'],
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])

df = df.apply(lambda x: np.square(x) if x.name in ['a','e','i','o','u'] else x,axis=1)

df

   Field_1  Field_2  Field_3
a    225.0     6.25  10000.0
b     20.0     4.50     50.0
c     25.0     5.20     80.0
d     45.0     5.80     48.0
e   1600.0    39.69   4900.0
f     41.0     6.40     90.0
g     51.0     2.30    111.0

### Lambda Function on Multiple Rows and Columns Simultaneously

In [15]:
values_list = [[1.5, 2.5, 10.0], [2.0, 4.5, 5.0], [2.5, 5.2, 8.0],
               [4.5, 5.8, 4.8], [4.0, 6.3, 70], [4.1, 6.4, 9.0],
               [5.1, 2.3, 11.1]]

df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'],
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])

df = df.apply(lambda x: np.square(x) if x.name in ['b', 'f'] else x, axis=1)
df = df.assign(Product=lambda x: (x['Field_1'] * x['Field_2'] * x['Field_3']))
df

   Field_1  Field_2  Field_3     Product
a     1.50     2.50     10.0     37.5000
b     4.00    20.25     25.0   2025.0000
c     2.50     5.20      8.0    104.0000
d     4.50     5.80      4.8    125.2800
e     4.00     6.30     70.0   1764.0000
f    16.81    40.96     81.0  55771.5456
g     5.10     2.30     11.1    130.2030