In [1]:
import numpy as np
import pandas as pd

# Grouping Rows in pandas

In [2]:
example = {'Team':['Arsenal', 'Manchester United', 'Arsenal',
                   'Arsenal', 'Chelsea', 'Manchester United',
                   'Manchester United', 'Chelsea', 'Chelsea', 'Chelsea'],
                   
           'Player':['Ozil', 'Pogba', 'Lucas', 'Aubameyang',
                       'Hazard', 'Mata', 'Lukaku', 'Morata', 
                                         'Giroud', 'Kante'],
                                         
           'Goals':[5, 3, 6, 4, 9, 2, 0, 5, 2, 3] }

df = pd.DataFrame(example)

In [3]:
df

                Team      Player  Goals
0            Arsenal        Ozil      5
1  Manchester United       Pogba      3
2            Arsenal       Lucas      6
3            Arsenal  Aubameyang      4
4            Chelsea      Hazard      9
5  Manchester United        Mata      2
6  Manchester United      Lukaku      0
7            Chelsea      Morata      5
8            Chelsea      Giroud      2
9            Chelsea       Kante      3

In [5]:
total_goals = df['Goals'].groupby(df['Team'])
print(total_goals.mean())

Team
Arsenal              5.000000
Chelsea              4.750000
Manchester United    1.666667
Name: Goals, dtype: float64

In [7]:
example = {'Team':['Australia', 'England', 'South Africa',
                   'Australia', 'England', 'India', 'India',
                        'South Africa', 'England', 'India'],
                        
           'Player':['Ricky Ponting', 'Joe Root', 'Hashim Amla',
                     'David Warner', 'Jos Buttler', 'Virat Kohli',
                     'Rohit Sharma', 'David Miller', 'Eoin Morgan',
                                                 'Dinesh Karthik'],
                                                 
          'Runs':[345, 336, 689, 490, 989, 672, 560, 455, 342, 376],
          
          'Salary':[34500, 33600, 68900, 49000, 98899,
                    67562, 56760, 45675, 34542, 31176] }

df = pd.DataFrame(example)
df

           Team          Player  Runs  Salary
0     Australia   Ricky Ponting   345   34500
1       England        Joe Root   336   33600
2  South Africa     Hashim Amla   689   68900
3     Australia    David Warner   490   49000
4       England     Jos Buttler   989   98899
5         India     Virat Kohli   672   67562
6         India    Rohit Sharma   560   56760
7  South Africa    David Miller   455   45675
8       England     Eoin Morgan   342   34542
9         India  Dinesh Karthik   376   31176

In [8]:
total_runs = df['Runs'].groupby(df['Team'])
print(total_runs.mean())

Team
Australia       417.500000
England         555.666667
India           536.000000
South Africa    572.000000
Name: Runs, dtype: float64